### ISSUE TITLE
Incorrect dependencies

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/optlang-feedstock#19]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

For at least several versions, the dependencies of this package on conda-forge have diverged from the dependencies as reported in the setup.cfg file for this package in github.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by Midnighter** [comment]
Please note that the dependencies were always only given as lower bounds. So I don't think that they diverged very much in practice.

Nevertheless, in #21 I have adjusted the dependency pins to be closer to one another.
