### ISSUE TITLE
Upcoming changes

### ISSUE THREAD

**Issue by Midnighter** [conda-forge/optlang-feedstock#8]
Hi @druvus,

Can you please add me as a maintainer to the recipe here? We will move the optlang repository from the biosustain organization to opencobra so there will be a few changes that I'd like to make here.

**Comment by druvus** [comment]
Hi @Midnighter 
I am currently only on a mobile so could you create a PR adding your github-id to meta.yaml recipe-maintainer list? I will then approve it asap.

**Comment by druvus** [comment]
thanks @Midnighter 
the PR passed after I re-rendered it and it is now merged.
